version: '3'

services:
  app:
    container_name: teste-pipeline
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - PORT=3000
    ports:
      - 3000:3000